[default]
locale = 'en-us'
extend-ignore-re = [
  "(?Rm)^.*(<!--|#|//)\\s*spellchecker:disable-line(-->|\n)?$",
  "(?s)(<!--|#|//)\\s*spellchecker:off\\s*(-->|\n).*?(<!--|#|//)\\s*spellchecker:on",
]

[default.extend-words]
typia = "typia"

[files]
extend-exclude = [
  "*.json",
  "AutoViewIconName.ts",
  "*.test.ts",
  "research/components/**/*",
  "research/mock-data/**/*",
  "research/swaggers/**/*"
]
